# docker-compose.yml
version: '3'

services:

  sy-classes:
    build: .
    command: >
       bash -c "python3 manage.py migrate
       && python3 manage.py collectstatic --noinput
       && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8006:8000"
    volumes:
      - .:/app
      - /usr/share/nginx/html/django-sy-classes/static:/static
