# Generated by Django 4.2.1 on 2023-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_title_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
