# Generated by Django 4.2.1 on 2023-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание'),
        ),
    ]
