# Generated by Django 4.2.1 on 2023-11-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course', verbose_name='Учебный курс'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='course.module', verbose_name='Раздел модуля')),
            ],
            options={
                'verbose_name': 'Раздел модуля',
                'verbose_name_plural': 'Разделы модуля',
            },
        ),
    ]
