# Generated by Django 4.2.1 on 2023-11-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_module_course_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Что')),
                ('answer', models.CharField(max_length=100, verbose_name='Значение')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема факта')),
                ('source', models.CharField(max_length=100, verbose_name='Источник факта')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
            },
        ),
        migrations.AlterField(
            model_name='part',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='course.module', verbose_name='Модуль'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(verbose_name='Номер урока')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='course.part', verbose_name='Раздел')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='course.relation', verbose_name='Изучаемый факт')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
